exports = module.exports = Object.create(null);

exports.issue = require("./issue");
exports.pull_request = require("./pull_request");
exports.comment = require("./comment");
exports.number_of_comments = require("./number_of_comments");
exports.threshold = require("./threshold");
exports.label = require("./label");
exports.open = require("./open");
exports.age = require("./age");
exports.last_action_age = require("./last_action_age");
exports.not = require("./not");
exports.any = require("./any");
exports.all = require("./all");
exports.in_order = require("./in_order");
exports.commit = require("./commit");
exports.review = require("./review");
exports.status = require("./status");
exports.check = require("./check");
exports.ensure = require("./ensure");
exports.permission = require("./permission");
exports.travis_job = require("./travis_job");
exports.fetch = require("./fetch");
exports.match = require("./match");
exports.string_cleanup = require("./string_cleanup");
